id: 2c4301737a844208be6b608ed668f076
initial_creation_type: ocr
source_metadata:
  volumes:
    7e3d3455a01c4d1f92f61924aba4b678:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
